### ISSUE TITLE
fico tomando dc

### ISSUE THREAD

**Issue by Zizi69** [klister803/WOWPPA#10]
não consigo nem ficar 5min logado no server que ja tomo dc, alguem sabe arruma isso ou só o server q ta ruim msm, pq ontem eu tava jogando normal.

**Comment by klister803** [comment]
Provavelmente é sua internet.

**Comment by Zizi69** [comment]
dificil se la
aqui é 100mb de fibra


2018-07-29 18:57 GMT-03:00 pedroevil51 <notifications@github.com>:

**Comment by klister803** [comment]
Complicado, não sei oque pode ser, tente trocar seu DNS para 
8.8.8.8 e 8.8.4.4
