### ISSUE TITLE
[QUEST]

### ISSUE THREAD

**Issue by iMilkbarr** [klister803/WOWPPA#11]
Nome da quest: The Valiant's Challenge
O que deveria acontecer: Ao ganhar do Argent Crusader, contar "Argent Champion Defeated: 1/1"
O que acontece: Mesmo ganhando do individuo, a quest não avança, não conta que você o derrotou.

**Comment by klister803** [comment]
Resolvido

**Comment by iMilkbarr** [comment]
Então, ao que parece no momento o Squire Danny agora não da a opção de "i'm ready to fight" ou quando da, e é apertado, ele faz a musica de entrada do argent champion mas ele não vem, logo não é possivel lutar com ele pra terminar a quest.

**Comment by klister803** [comment]
Fiz o teste, o champion veio e eu consegui completar a quest normalmente, pode tentar novamente?

**Comment by iMilkbarr** [comment]
Agora funcionou, na hora eu tentei umas 5 vezes, até tirei e coloquei a quest dnv pra ver kk, ele fazia a musica, mas o champion n andava até a batalha ;-;  bomm, muito obgd
