### ISSUE TITLE
[QUEST] Quest bugada 

### ISSUE THREAD

**Issue by Rickzinho** [klister803/WOWPPA#13]
Olá, sou um jogador novato e eu e minha party estamos tendo uns problemas com uma quest que ta bugada, tem que matar um mob, Só que ele não aparece de jeito nenhum, o mob que não aparece é o Borgoth the bloodletter e a missão se chama Dar'khan's Lieutenants, POr favor se conseguir desbugar ela nós agradeceremos muito.Obrigado.

**Comment by klister803** [comment]
Obrigado pelo report, e foi resolvido
