### ISSUE TITLE
QUEST

### ISSUE THREAD

**Issue by SeexyStyle** [klister803/WOWPPA#14]
[20] Dar'Khan's Lieutenants
Oque deveria acontecer: Spawn de 4 mobs ''chefes''
Como está acontecendo: Não spawna 2: Borgoth the Bloodletter e Masophet the black

**Comment by klister803** [comment]
Não consegui replicar o erro, invalido
Os dois npcs estão spawnados 
(Apenas tem um tempo de respawn alto)
[Print 1](https://i.imgur.com/vciUsub.jpg)
[Print 2](https://i.imgur.com/ZfYvexI.jpg)
