### ISSUE TITLE
[QUEST] The Wayward Aprendice

### ISSUE THREAD

**Issue by Saborte** [klister803/WOWPPA#16]
Oque deveria acontecer:
Entregar a quest pro NPC normal.

Como está acontecendo:
O NPC não tem o ponto de interrogação na cabeça apesar de aperecer no mapa e nem abre pra conversação.
![1](https://user-images.githubusercontent.com/41928971/43427467-0a720e08-9430-11e8-854d-8e01bccfe5be.png)
![2](https://user-images.githubusercontent.com/41928971/43427470-0a9b17ee-9430-11e8-922a-28c8ffeba122.png)

**Comment by Saborte** [comment]
Nome da quest é The Wayward Aprendice

**Comment by klister803** [comment]
Creio que o problema foi resolvido, obrigado pelo report
