### ISSUE TITLE
[QUEST]

### ISSUE THREAD

**Issue by igorfelipedev** [klister803/WOWPPA#17]
https://youtu.be/vu7wB6JSsxs
Quando estou em "Brunnhildar Village" o NPC ta lá quando me aproximo e muda para Valley of ancient winter o NPC some
Bug Quest: You'll Need a Bear (part 12 of 16) [ID: 12972]

**Comment by klister803** [comment]
Estamos observando este problema, está acontecendo com varios npcs e mineração

**Comment by igorfelipedev** [comment]
nada ainda né man =/

**Comment by klister803** [comment]
Ainda não amigo :( estou contratando um desenvolvedor pra me ajudar
