### ISSUE TITLE
Chain de quest: Quel'Delar

### ISSUE THREAD

**Issue by Goranxd** [klister803/WOWPPA#2]
Quest: Thalorien Dawnseeker

Oque deveria acontecer: Encontrar o NPC e matar um Elite 80 perto dele para receber a benção e assim ficar phased em Sunwell.

Como está acontecendo: O NPC está parado e não há interação com ele e nem o elite. (Jeff completou a quest)

Quest: The Purification of Quel'Delar 

Oque deveria acontecer: falar com NPC na porta da raid e ser teleportado para a sala onde fica a Sunwell. (http://pt.wowhead.com/quest=24553/a-purifica%C3%A7%C3%A3o-da-queldelar#english-comments)

Como está acontecendo: O NPC que me teleportaria não aparece e mesmo sendo spawnado (pelo jeff) não há interação com ele. se eu tentar entrar em sunwell, entro na raid normal sem o evento.

as outras quests da chain estão normais, com 1 pequeno bug na quest de halls of reflection, mas quando abandonei e peguei denovo funcionou normalmente

**Comment by klister803** [comment]
Hum, interessante, vou dar uma olhada (Posso ter desabilitado a quest por algum motivo no passado)

**Comment by klister803** [comment]
Resolvido, qualquer problema me avise.
