### ISSUE TITLE
[QUEST] What Do You Feed a Yeti Anyway ? (Diaria "importante")

### ISSUE THREAD

**Issue by iMilkbarr** [klister803/WOWPPA#20]
Local de inicio: Argent Crusaders (nome da quest no titulo)
Como deveria funcionar: No barco que fica descendo o penhasco ao lado dos argentcrusaders, onde existem 3 corpos de tubarão, os baldes que possuem nesse barco deveriam dar um item que vc invoca novos tubarões, pra matar e receber a carne exigida na missão.
Como esta funcionando: Os baldes do barco não são usaveis, logo é impossivel pegar o item que faz aparecerem os tubarões.

**Comment by gtoledo99** [comment]
Não esta bugada, é só entrar na água para usar os baldes
