### ISSUE TITLE
Dungeon Bug

### ISSUE THREAD

**Issue by Lilithy1000** [klister803/WOWPPA#24]
Azjol-Nerub esta bugada demais, eu e outros que tentaram ela varias vezes percebemos que o spawn rate esta errado, Onde e para spawar 3 mobs por puxe, esta spawnando 6, fazendo ela impossivel para o atual nivel e possivelmente ate para um possivel heroic nela.

**Comment by klister803** [comment]
Resolvido, obrigado pelo report
