### ISSUE TITLE
Criação de personagem

### ISSUE THREAD

**Issue by LegoMacman** [klister803/WOWPPA#26]
Não consigo criar um gnomo mago homem

estou colocando gnomo, mago, homem e não vai, n importa o nome que eu coloque, porem se eu mudar a raça, classe ou sexo, funciona!

**Comment by klister803** [comment]
É um bug que temos noção, ele é referente ao cliente que você usa, apenas troque o cabelo /barba do seu personagem que vai funcionar

**Comment by LegoMacman** [comment]
eu troquei o cabelo e deu certo =D fiz no mesmo dia

Em sex, 3 de ago de 2018 às 23:16, pedroevil51 <notifications@github.com>
escreveu:
