### ISSUE TITLE
Cadastro Bugado

### ISSUE THREAD

**Issue by Ioliii** [klister803/WOWPPA#4]
An Error Was Encountered
The action you have requested is not allowed.

Isso acontece sempre que tento criar uma conta, acredito que por conta do Email que não dá o aprovado, já tentei várias vezes, com emails diferentes, em locais diferentes e com navegadores diferentes e dá na mesma.

**Comment by klister803** [comment]
Por favor entre em contato com Blue no discord https://discord.gg/GkjWMA 
O Erro está provavelmente na sua internet, mas fale com ele que ele criara uma conta para você.
