### ISSUE TITLE
Quest "Battle of the Crismon Watch"

### ISSUE THREAD

**Issue by kevinwp** [klister803/WOWPPA#48]
Pra fazer é simples, pegar a quest, esperar os demonios darem spawn para matar, depois de esperar a conversa dos mobs e aguardar os proximos mobs darem spawn. Eu matei os primeiros demonios e o resto não deu spawn, fiquei aguardando quase 3 minutos e nada aconteceu ( pra uma simples quest 3 minutos é muito ). Abandonei a quest para fazer denovo e nada ocorreu, dei reload, reloguei e o mesmo problema persistiu. Todo servidor de wow que eu entro eu faço essa quest, não é normal ela demorar muito, em média 5 minutos ela está completa até menos. 
Desde já agradeço,
Cordialmente,
Sorrow.

**Comment by klister803** [comment]
Fix temporario.
