### ISSUE TITLE
Token de Level 80

### ISSUE THREAD

**Issue by OzWiLy** [klister803/WOWPPA#65]
eu comprei Token de Level 80, e não veio, chatiado :(

**Comment by OzWiLy** [comment]
????????????????????????????????????????????????????????????????

**Comment by klister803** [comment]
Opa ozwily, você pode falar com algum gm no discord, de preferencia o scott, que ele lhe entregara o level 80

**Comment by OzWiLy** [comment]
E TOKEN PRO LVL 80, tipo dae troca por um item


2018-08-15 12:49 GMT-03:00 pedroevil51 <notifications@github.com>:
