### ISSUE TITLE
[Quest] Into the Realm of Shadows bugada

### ISSUE THREAD

**Issue by ubir** [klister803/WOWPPA#71]
Quest ta bugada, no mundo das trevas era pra ter os cavalos com os cavaleiros que devemos derrotar, mas ele n aparece e n consigo subir no cavalo

**Comment by ubir** [comment]
![wowscrnshot_081418_202042](https://user-images.githubusercontent.com/42393969/44124425-90f3c5f0-a003-11e8-9aed-1785f7668e7b.jpg)
![wowscrnshot_081418_202023](https://user-images.githubusercontent.com/42393969/44124429-9714fdaa-a003-11e8-89d4-f8ae408e1e18.jpg)

**Comment by klister803** [comment]
Obrigado por reportar, quest setada para autocompletar temporariamente
