### ISSUE TITLE
JOGO NÃO ESTA LOGANDO 

### ISSUE THREAD

**Issue by FGD862** [klister803/WOWPPA#74]
MEU JOGO ENTRA NORMAL AI ELE FALA QUE ESTA COM UM PROBLEMA NO SEVER E FALA PRA MIM LOGAR MAIS TARDE OU ENTRAR CONTADO COM O SITE "https://us.battle.net/support/en/games/wow" NÃO SEI OQUE FAZER  ALGUÉM PODE ME AJUDAR

**Comment by Cratola** [comment]
O MEU TAMBEM NAO SEI O QUE FAZER
