### ISSUE TITLE
NETHERWING QUESTS

### ISSUE THREAD

**Issue by Danodanodano** [klister803/WOWPPA#77]
Após finalizar a sequência de 7 quests iniciadas pelo NPC "Mordenai" e ganhar a conquista de Exaltado com Netherwing, ainda estava em combate com os orcs da base em Netherwing Ledge. Amigo meu consegue fazer as quests diárias de la, mas eu não. Segundo ele eu teria que pegar mais uma quest com o Mordenai no final, mas não tem nenhuma que eu possa pegar.

Resumindo, estou Exaltado com Netherwing mas não consigo interagir com os npcs da base, não tenho quests em nenhum lugar.

**Comment by ataron157** [comment]
pelo que pesquisei tem que ter rading 300
