### ISSUE TITLE
Bug em na quest  [[80] The Black Knight's Fall]

### ISSUE THREAD

**Issue by derica007** [klister803/WOWPPA#84]
Eu mato o NPC e não completa  a quest(sim, eu to fazendo certo, eu  vi em um video e eu estou fazendo igualzinhp) e o cara fica morto no  chão  e me batendo e u  não consigo bater no NPC e eu preciso fazer  essa quest e ele fica em Argent Tourname

**Comment by klister803** [comment]
Fix temporario aplicado
