### ISSUE TITLE
[GERAL]

### ISSUE THREAD

**Issue by dantenier** [klister803/WOWPPA#9]
Essa TAG não existe mais eu não achei uma que se encaixasse melhor no contexto.

Vou resumir e depois explicar detalhadamente.
O que está acontecendo: Quando você está em uma área, vendo um item ou mob/npc que esteja na divisa para outra área, o mesmo acaba sumindo, se este item ou mob estiver setado para área x, porém esteja na área y que são coladas e você acabe indo para área y para pegar/matar, ele some. 
Eu sei que ficou confuso, então gravei um vídeo:
https://youtu.be/2VXX77Qs1RQ

Como deveria funcionar: Basicamente não devia sumir quando se troca de área

**Comment by klister803** [comment]
Wow, isso é realmente muito estranho, vou dar uma olhada nisso

**Comment by klister803** [comment]
O Problema não era o servidor, depois de um tempo descobrimos que o jogador estava em uma quest que mudava a phasing quando ele entrava na outra area
